# E-Paper Display GPIO Pin Numbers
GPIO_EPD_SCK = 18
GPIO_EPD_MOSI = 19
GPIO_EPD_CS = 17
GPIO_EPD_DC = 20
GPIO_EPD_RST = 21
GPIO_EPD_BUSY = 16

# IR GPIO Pin Numbers
GPIO_IR_RX = 10
GPIO_IR_TX = 11

# Button GPIO Pin Numbers
GPIO_CHANGE_IR_PROTOCOL_BUTTON = 9
GPIO_TRANSMIT_IR_BUTTON = 14
GPIO_MENU_SELECT_BUTTON = 15
GPIO_LEARN_IR_BUTTON = 8

# Battery GPIO Pin Numbers
VOLTAGE_DIVIDER_PIN = 26

# Events
BUTTON_PRESSED = "BUTTON_PRESS"
BUTTON_RELEASED = "BUTTON_RELEASE"
DEVICE_CHANGED = "DEVICE_CHANGED"
IR_PROTOCOL_CHANGED = "IR_PROTOCOL_CHANGED"
IR_RECEIVED = "IR_RECEIVED"
IR_TRANSMITTED = "IR_TRANSMITTED"
LOW_BATTERY = "LOW_BATTERY"

# Buttons
MENU_SELECT_BUTTON = "menu_select"
CHANGE_IR_PROTOCOL_BUTTON = "change_ir_protocol"
TRANSMIT_IR_BUTTON = "transmit_ir"
LEARN_IR_BUTTON = "learn_ir"
