# E-Paper Display GPIO Pin Numbers
EPD_SCK = 18
EPD_MOSI = 19
EPD_CS = 17
EPD_DC = 20
EPD_RST = 21
EPD_BUSY = 16

# IR GPIO Pin Numbers
IR_RX = 10
IR_TX = 11

# Button GPIO Pin Numbers
IR_PROTOCOL_BUTTON = 9
IR_TX_BUTTON_1 = 14
EPD_BUTTON1 = 15
LEARN_IR_BUTTON1 = 8

# Battery GPIO Pin Numbers
VOLTAGE_DIVIDER_PIN = 26

# Events
BUTTON_PRESSED = "BUTTON_PRESS"
BUTTON_RELEASED = "BUTTON_RELEASE"
DEVICE_CHANGED = "DEVICE_CHANGED"
IR_PROTOCOL_CHANGED = "IR_PROTOCOL_CHANGED"
IR_RECEIVED = "IR_RECEIVED"
IR_TRANSMITTED = "IR_TRANSMITTED"
LOW_BATTERY = "LOW_BATTERY"

# Buttons
MENU_SELECT_BUTTON = "menu_select"
CHANGE_IR_PROTOCOL_BUTTON = "change_ir_protocol"
TRANSMIT_IR_BUTTON = "transmit_ir"
LEARN_IR_BUTTON = "learn_ir"
